name: Metrics
on:
  push:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar gráfico de meio ano
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ezezz7
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year 
