#aaaa
name: Metrics
on:
  push: # Rodará toda vez que um commit for feito
  workflow_dispatch: # Permite rodar manualmente

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar métricas do GitHub
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ezezz7
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Mostra o ano todo
